### ISSUE TITLE
Has the  setTitleBarHint() been implemented ?

### ISSUE THREAD

**Issue by Drezzler** [yjg30737/pyqt-frameless-window#6]
Hi, as the title says, has Has the  setTitleBarHint() been implemented ?

I am trying to show only maximize button in window/dialog, but for some reason, it is not working.

I have tried setting titlebar hints with 

`titleBar.setTitleBarHint(['max'])`

But all three buttons still show.

**Comment by yjg30737** [comment]
That was indeed implemented but it would've not worked like that way because it only had the "print" function at that time, for testing.

I should've been explained that in commit message. Sorry for that

I've just changed up a bit to make `setTitleBarHint` work and it works like a charm (to me, at least).

Oh by the way happy new year.

If you have any questions feel free to ask 🙂

**Comment by Drezzler** [comment]
Thank you. 

It works now.
